import Stepper from '../components/Stepper.jsx'
import FamilyTreeIcon from '../components/FamilyTreeIcon.jsx'
import ConnectHealthHubBanner from '../components/ConnectHealthHubBanner.jsx'
import ManualEntry from '../components/ManualEntry.jsx'
import { buildRiskSummary, LDL_THRESHOLD } from '../logic.js'

// Screen 2: a personalised "why this matters to me" summary.
// The content is generated by buildRiskSummary() from the patient data,
// so changing the LDL value changes what's shown here.
export default function WhyThisMatters({
  patient,
  updatePatient,
  isManual,
  showConnect,
  onConnect,
  onContinue,
}) {
  const hasLdl = patient.ldlValue != null && patient.ldlValue !== ''
  const summary = hasLdl ? buildRiskSummary(patient, LDL_THRESHOLD) : null

  return (
    <section className="screen">
      <Stepper currentStage={1} />

      {showConnect && <ConnectHealthHubBanner onConnect={onConnect} />}

      <div className="card">
        <span className="eyebrow">Why this matters to you</span>
        <h1 className="screen-title">Let&apos;s make sense of your result</h1>

        {isManual && !hasLdl && (
          <ManualEntry patient={patient} updatePatient={updatePatient} />
        )}

        {!hasLdl ? (
          <p className="body-text">
            Enter your LDL cholesterol value above and we&apos;ll put together a
            short, personalised summary just for you.
          </p>
        ) : (
          <>
            <div className="highlight">
              <p className="highlight-label">Your LDL reading</p>
              <p className="highlight-value">
                {patient.ldlValue} <span className="unit">mmol/L</span>
              </p>
              <p className="highlight-note">
                This is above the {LDL_THRESHOLD} mmol/L level we look out for
                {summary.aboveThreshold > 0
                  ? ` — by ${summary.aboveThreshold} mmol/L.`
                  : '.'}
              </p>
            </div>

            <p className="lead explain">{summary.intro}</p>

            <div className="info-list">
              {summary.points.map((point) => {
                const isFamily = point.title.toLowerCase().includes('family')
                return (
                  <div
                    className={`info-item${isFamily ? ' family' : ''}`}
                    key={point.title}
                  >
                    <div className="family-head">
                      {isFamily && <FamilyTreeIcon size={24} />}
                      <h2 className="info-title">{point.title}</h2>
                    </div>
                    <p className="info-body explain">{point.body}</p>
                  </div>
                )
              })}
            </div>
          </>
        )}

        <button className="btn btn-primary" onClick={onContinue}>
          Continue
        </button>
      </div>
    </section>
  )
}
